import React, { useState, useEffect } from 'react';
import './SetupWizard.css';

const STEPS = [
  { stepKey: 'credentials', title: 'PingOne Credentials', number: 1 },
  { stepKey: 'apps',        title: 'Create Application',  number: 2 },
  { stepKey: 'resources',   title: 'Create Resource Server', number: 3 },
  { stepKey: 'scopes',      title: 'Create Scopes',       number: 4 },
  { stepKey: 'spel',        title: 'SPEL Attribute Mapping', number: 5 },
  { stepKey: 'envfile',     title: 'Generate .env',       number: 6 },
  { stepKey: 'complete',    title: 'Complete',             number: 7 },
];

const STEP_INDEX = Object.fromEntries(STEPS.map((s, i) => [s.stepKey, i]));

const SSE_TO_STEP = {
  'validate': 'credentials',
  'resource-server': 'resources', 'mcp-resource-server': 'resources',
  'scopes': 'scopes', 'mcp-scopes': 'scopes',
  'admin-app': 'apps', 'user-app': 'apps', 'mcp-app': 'apps', 'worker-app': 'apps', 'mcp-exchanger-app': 'apps',
  'schema-attr': 'spel', 'spel-claim': 'spel',
  'config': 'envfile',
  'complete': 'complete'
};

const STEP_ORDER = ['credentials', 'apps', 'resources', 'scopes', 'spel', 'envfile', 'complete'];

const streamSSEResponse = async (response, onStep, onComplete, onError) => {
  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = '';
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\n');
      buffer = lines.pop();
      for (const line of lines) {
        if (line.startsWith('data: ')) {
          const data = line.slice(6);
          if (data === '[DONE]') { onComplete?.(); return; }
          try {
            const step = JSON.parse(data);
            onStep(step);
            if (step.step === 'complete' && step.result) { onComplete?.(step.result); return; }
          } catch (e) { /* skip malformed */ }
        }
      }
    }
  } finally {
    reader.releaseLock();
  }
};

const generateEnvContents = (result, creds) => [
  '# PingOne Configuration - Generated by Setup Wizard',
  `PINGONE_ENVIRONMENT_ID=${creds.envId}`,
  `PINGONE_REGION=${creds.region}`,
  '',
  '# Admin Application',
  `PINGONE_ADMIN_CLIENT_ID=${result.adminApp?.clientId || ''}`,
  'PINGONE_ADMIN_CLIENT_SECRET=<set-in-pingone-console>',
  `PINGONE_ADMIN_REDIRECT_URI=${creds.publicAppUrl}/api/auth/oauth/callback`,
  '',
  '# User Application',
  `PINGONE_CORE_CLIENT_ID=${result.userApp?.clientId || ''}`,
  'PINGONE_CORE_CLIENT_SECRET=<set-in-pingone-console>',
  `PINGONE_CORE_REDIRECT_URI=${creds.publicAppUrl}/api/auth/oauth/callback`,
  '',
  '# MCP Exchanger (Token Exchange)',
  `PINGONE_MCP_EXCHANGER_CLIENT_ID=${result.mcpExchangerApp?.clientId || ''}`,
  'PINGONE_MCP_EXCHANGER_CLIENT_SECRET=<set-in-pingone-console>',
  '',
  '# Resource Server',
  `ENDUSER_AUDIENCE=${result.resourceServer?.audience?.[0] || 'banking_api_enduser'}`,
  '',
  '# Demo Users',
  'DEMO_USER_USERNAME=bankuser',
  `DEMO_USER_PASSWORD=${result.bankUser?.password || 'BankUser123!'}`,
  'DEMO_ADMIN_USERNAME=bankadmin',
  `DEMO_ADMIN_PASSWORD=${result.bankAdmin?.password || 'BankAdmin123!'}`,
  '',
  '# Worker Credentials',
  `PINGONE_WORKER_CLIENT_ID=${creds.workerClientId}`,
  `PINGONE_WORKER_CLIENT_SECRET=${creds.workerClientSecret}`,
  '',
  '# MFA Step-up Configuration',
  `STEP_UP_ACR_VALUE=${creds.stepUpAcrValue || 'Multi_Factor'}`,
].join('\n');

function getStepCircleClass(stepKey, activeStep, stepStatuses) {
  const status = stepStatuses[stepKey];
  if (status === 'error') return 'error';
  if (status === 'success') return 'complete';
  if (STEP_INDEX[stepKey] === activeStep) return 'active';
  if (STEP_INDEX[stepKey] < activeStep) return 'complete';
  return 'incomplete';
}

export default function SetupWizard() {
  const [creds, setCreds] = useState({
    envId: '',
    workerClientId: '',
    workerClientSecret: '',
    region: 'com',
    publicAppUrl: window.location.origin.replace(':3000', ':4000'),
    stepUpAcrValue: 'Multi_Factor'
  });
  const [showSecrets, setShowSecrets] = useState({});
  const [credErrors, setCredErrors] = useState({});
  const [activeStep, setActiveStep] = useState(0);
  const [stepStatuses, setStepStatuses] = useState({});
  const [stepMessages, setStepMessages] = useState({});
  const [logEntries, setLogEntries] = useState([]);
  const [running, setRunning] = useState(false);
  const [provisionResult, setProvisionResult] = useState(null);
  const [envContents, setEnvContents] = useState('');
  const [copyToast, setCopyToast] = useState('');
  const [verifyError, setVerifyError] = useState('');
  const [verifyLoading, setVerifyLoading] = useState(false);

  // Resume from localStorage on mount
  useEffect(() => {
    try {
      const saved = JSON.parse(localStorage.getItem('pingoneSetupWizard.v1') || '{}');
      if (saved.completedSteps?.length) {
        const lastCompleted = saved.completedSteps[saved.completedSteps.length - 1];
        const idx = STEP_ORDER.indexOf(lastCompleted);
        setActiveStep(Math.min(idx + 1, 6));
        // Restore completed statuses (not secrets)
        const restoredStatuses = {};
        saved.completedSteps.forEach(sk => { restoredStatuses[sk] = 'success'; });
        setStepStatuses(restoredStatuses);
      }
    } catch (_) { /* ignore corrupt state */ }
  }, []);

  const validateCreds = () => {
    const errors = {};
    if (!creds.envId.trim()) errors.envId = 'Environment ID is required';
    if (!creds.workerClientId.trim()) errors.workerClientId = 'Worker Client ID is required';
    if (!creds.workerClientSecret.trim()) errors.workerClientSecret = 'Worker Client Secret is required';
    setCredErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const verifyConnection = async (e) => {
    e.preventDefault();
    if (!validateCreds()) return;
    setVerifyLoading(true);
    setVerifyError('');
    try {
      const res = await fetch('/api/admin/setup/validate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          envId: creds.envId,
          workerClientId: creds.workerClientId,
          workerClientSecret: creds.workerClientSecret,
          region: creds.region
        })
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error || `HTTP ${res.status}`);
      }
      setActiveStep(1);
      // Persist non-secret metadata
      try {
        const saved = JSON.parse(localStorage.getItem('pingoneSetupWizard.v1') || '{}');
        localStorage.setItem('pingoneSetupWizard.v1', JSON.stringify({
          ...saved,
          completedSteps: ['credentials'],
          publicAppUrl: creds.publicAppUrl,
          region: creds.region
        }));
      } catch (_) {}
    } catch (err) {
      setVerifyError(err.message);
    } finally {
      setVerifyLoading(false);
    }
  };

  const updateStepFromSSE = (event) => {
    const mappedKey = SSE_TO_STEP[event.step];
    if (!mappedKey) return;
    setStepMessages(prev => ({ ...prev, [event.step]: event.message }));
    setLogEntries(prev => [...prev, { icon: event.icon || '⚙️', message: event.message, step: event.step }]);
    if (event.icon === '✅') {
      setStepStatuses(prev => ({ ...prev, [mappedKey]: 'success' }));
    } else if (event.icon === '❌') {
      setStepStatuses(prev => ({ ...prev, [mappedKey]: 'error' }));
    } else {
      setStepStatuses(prev => {
        if (prev[mappedKey] !== 'success' && prev[mappedKey] !== 'error') {
          return { ...prev, [mappedKey]: 'running' };
        }
        return prev;
      });
    }
  };

  const runAll = async () => {
    setRunning(true);
    setLogEntries([]);
    try {
      const response = await fetch('/api/admin/setup/run', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify(creds)
      });
      if (!response.ok) {
        const body = await response.json().catch(() => ({}));
        throw new Error(body.error || `HTTP ${response.status}`);
      }
      await streamSSEResponse(
        response,
        (event) => { updateStepFromSSE(event); },
        (result) => {
          if (result) {
            setProvisionResult(result);
            setEnvContents(generateEnvContents(result, creds));
            setActiveStep(6);
            // Mark all steps success
            const allSuccess = {};
            STEPS.forEach(s => { allSuccess[s.stepKey] = 'success'; });
            setStepStatuses(allSuccess);
            // Persist completed steps (no secrets)
            try {
              localStorage.setItem('pingoneSetupWizard.v1', JSON.stringify({
                completedSteps: STEP_ORDER,
                createdIds: {
                  adminApp: result.adminApp?.clientId,
                  userApp: result.userApp?.clientId,
                  mcpApp: result.mcpApp?.clientId,
                  workerApp: result.workerApp?.clientId,
                  mcpExchangerApp: result.mcpExchangerApp?.clientId
                }
              }));
            } catch (_) {}
          }
          setRunning(false);
        },
        (err) => {
          setRunning(false);
        }
      );
    } catch (err) {
      setLogEntries(prev => [...prev, { icon: '❌', message: err.message, step: 'error' }]);
      setRunning(false);
    }
  };

  const retryStep = async (stepKey) => {
    setStepStatuses(prev => ({ ...prev, [stepKey]: 'running' }));
    try {
      const res = await fetch('/api/admin/setup/recreate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ stepKey, ...creds })
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      setStepStatuses(prev => ({ ...prev, [stepKey]: 'success' }));
    } catch (err) {
      setStepStatuses(prev => ({ ...prev, [stepKey]: 'error' }));
    }
  };

  const copyEnv = async () => {
    try {
      await navigator.clipboard.writeText(envContents);
      setCopyToast('Copied to clipboard');
    } catch (_) {
      setCopyToast('Copy failed — check browser permissions');
    }
    setTimeout(() => setCopyToast(''), 2000);
  };

  const startOver = () => {
    localStorage.removeItem('pingoneSetupWizard.v1');
    window.location.reload();
  };

  const toggleStep = (idx) => {
    // Only allow clicking completed or active steps
    if (idx <= activeStep) {
      setActiveStep(idx === activeStep ? idx : idx);
    }
  };

  const renderStepHeader = (step, idx) => {
    const circleClass = getStepCircleClass(step.stepKey, activeStep, stepStatuses);
    const isOpen = idx === activeStep;
    const isClickable = idx <= activeStep;
    return (
      <div
        className={`wizard-step-header${isOpen ? ' open' : ''}${isClickable ? ' clickable' : ''}`}
        onClick={() => isClickable && toggleStep(idx)}
        role="button"
        aria-expanded={isOpen}
      >
        <div className={`step-circle ${circleClass}`}>{step.number}</div>
        <div style={{ flex: 1 }}>
          <div className="wizard-step-title">{step.title}</div>
        </div>
        <span className="wizard-step-chevron">{isOpen ? '▲' : '▼'}</span>
      </div>
    );
  };

  const renderCredentialsPanel = () => (
    <form onSubmit={verifyConnection}>
      <div className="wizard-field">
        <label className="wizard-label">Environment ID *</label>
        <input
          className="wizard-input"
          type="text"
          value={creds.envId}
          onChange={e => setCreds(p => ({ ...p, envId: e.target.value }))}
          placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        />
        {credErrors.envId && <div className="wizard-error">{credErrors.envId}</div>}
      </div>
      <div className="wizard-field">
        <label className="wizard-label">Worker Client ID *</label>
        <input
          className="wizard-input"
          type="text"
          value={creds.workerClientId}
          onChange={e => setCreds(p => ({ ...p, workerClientId: e.target.value }))}
          placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        />
        {credErrors.workerClientId && <div className="wizard-error">{credErrors.workerClientId}</div>}
      </div>
      <div className="wizard-field">
        <label className="wizard-label">Worker Client Secret *</label>
        <div className="wizard-input-wrap">
          <input
            className="wizard-input"
            type={showSecrets.workerClientSecret ? 'text' : 'password'}
            value={creds.workerClientSecret}
            onChange={e => setCreds(p => ({ ...p, workerClientSecret: e.target.value }))}
            placeholder="••••••••••••••••"
            style={{ paddingRight: 36 }}
          />
          <button
            type="button"
            className="wizard-eye-btn"
            onClick={() => setShowSecrets(p => ({ ...p, workerClientSecret: !p.workerClientSecret }))}
            aria-label={showSecrets.workerClientSecret ? 'Hide secret' : 'Show secret'}
          >
            {showSecrets.workerClientSecret ? '🙈' : '👁️'}
          </button>
        </div>
        {credErrors.workerClientSecret && <div className="wizard-error">{credErrors.workerClientSecret}</div>}
      </div>
      <div className="wizard-field">
        <label className="wizard-label">Region</label>
        <select
          className="wizard-select"
          value={creds.region}
          onChange={e => setCreds(p => ({ ...p, region: e.target.value }))}
        >
          <option value="com">North America (com)</option>
          <option value="eu">Europe (eu)</option>
          <option value="ca">Canada (ca)</option>
          <option value="ap">Asia-Pacific (ap)</option>
        </select>
      </div>
      <div className="wizard-field">
        <label className="wizard-label">App URL</label>
        <input
          className="wizard-input"
          type="text"
          value={creds.publicAppUrl}
          onChange={e => setCreds(p => ({ ...p, publicAppUrl: e.target.value }))}
          placeholder="https://api.pingdemo.com:4000"
        />
      </div>
      <div className="wizard-field">
        <label className="wizard-label">Step-up ACR Value</label>
        <input
          className="wizard-input"
          type="text"
          value={creds.stepUpAcrValue}
          onChange={e => setCreds(p => ({ ...p, stepUpAcrValue: e.target.value }))}
          placeholder="Multi_Factor"
        />
      </div>
      {verifyError && <div className="wizard-error" style={{ marginBottom: 12 }}>{verifyError}</div>}
      <button type="submit" className="wizard-btn-primary" disabled={verifyLoading}>
        {verifyLoading ? 'Verifying...' : 'Verify Connection'}
      </button>
    </form>
  );

  const renderProvisioningPanel = (step) => {
    const relevantLogs = logEntries.filter(e => SSE_TO_STEP[e.step] === step.stepKey);
    const status = stepStatuses[step.stepKey];
    return (
      <div>
        {relevantLogs.length > 0 && (
          <ul className="wizard-log">
            {relevantLogs.map((entry, i) => (
              <li key={i} className="wizard-log-entry">
                <span className="wizard-log-icon">{entry.icon}</span>
                <span>{entry.message}</span>
              </li>
            ))}
          </ul>
        )}
        {relevantLogs.length === 0 && !running && (
          <p style={{ color: '#6b7280', fontSize: 14 }}>Waiting to run...</p>
        )}
        {status === 'error' && (
          <button className="wizard-btn-secondary" onClick={() => retryStep(step.stepKey)} style={{ marginTop: 8 }}>
            Retry
          </button>
        )}
      </div>
    );
  };

  const renderRunPanel = () => (
    <div>
      {logEntries.length > 0 && (
        <ul className="wizard-log">
          {logEntries.map((entry, i) => (
            <li key={i} className="wizard-log-entry">
              <span className="wizard-log-icon">{entry.icon}</span>
              <span>{entry.message}</span>
            </li>
          ))}
        </ul>
      )}
      {!running && activeStep === 1 && (
        <button className="wizard-btn-primary" onClick={runAll}>
          Run All →
        </button>
      )}
      {running && <p style={{ color: '#6b7280', fontSize: 14 }}>Provisioning in progress...</p>}
    </div>
  );

  const renderCompletionPanel = () => (
    <div>
      <div className="wizard-complete-banner">
        <div className="wizard-complete-title">🎉 Setup Complete</div>
        <ul className="wizard-checklist">
          <li>✓ Application created</li>
          <li>✓ Resource server created</li>
          <li>✓ Scopes created</li>
          <li>✓ SPEL mapping configured</li>
          <li>✓ .env generated</li>
        </ul>
      </div>
      <div className="wizard-code-block">{envContents}</div>
      <div className="wizard-complete-actions">
        <button className="wizard-btn-primary" onClick={copyEnv}>
          📋 Copy .env
        </button>
        {copyToast && <span className="wizard-copy-toast">{copyToast}</span>}
        <button
          className="wizard-btn-secondary"
          onClick={() => { window.location.href = '/dashboard'; }}
        >
          Open Dashboard →
        </button>
        <button className="wizard-btn-secondary" onClick={startOver}>
          Start Over
        </button>
      </div>
    </div>
  );

  const renderPanelContent = (step, idx) => {
    if (idx === 0) return renderCredentialsPanel();
    if (idx === 6) return renderCompletionPanel();
    // Steps 1-5: show run button on step 1, provisioning log on steps 2-5
    if (idx === 1) return renderRunPanel();
    return renderProvisioningPanel(step);
  };

  return (
    <div className="setup-wizard">
      <h1 className="setup-wizard-title">BX Finance — PingOne Setup</h1>
      {STEPS.map((step, idx) => (
        <div className="wizard-step" key={step.stepKey}>
          {renderStepHeader(step, idx)}
          {idx === activeStep && (
            <div className="wizard-step-panel">
              {renderPanelContent(step, idx)}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}
